#! /bin/sh
#
_TIME_Y=`date +%-Y`
_TIME_m=`date +%-m`
_TIME_d=`date +%-d`
_TIME_H=`date +%-H`
_TIME_M=`date +%-M`
_TIME_S=`date +%-S`
ASMDATE=`date -u +".long "%Y%m%d`
CC=${CC:-gcc}
NOBUILDID=${NOBUILDID:-0}

if [ "$NOBUILDID" = "0" ]; then
	BUILDID=-Wl,--build-id=none
else
	BUILDID=
fi

echo "#define _TIME_Y $_TIME_Y" >fat_config.h
echo "#define _TIME_m $_TIME_m" >>fat_config.h
echo "#define _TIME_d $_TIME_d" >>fat_config.h
echo "#define _TIME_H $_TIME_H" >>fat_config.h
echo "#define _TIME_M $_TIME_M" >>fat_config.h
echo "#define _TIME_S $_TIME_S" >>fat_config.h
echo "#define GET_FATTIME" >>fat_config.h
gcc -I../../include/ -DASM_BUILD_DATE="\"$ASMDATE"\" -m32 -mno-sse -nostdlib -fno-reorder-functions -fno-strict-aliasing -fno-exceptions -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-zero-initialized-in-bss -fno-function-cse -fno-jump-tables --entry main -Wl,-N $BUILDID -fPIE -Wl,-Ttext -Wl,0 fat.c -o fat.o
gcc -I../../include/ -DFAT_MINI -DASM_BUILD_DATE="\"$ASMDATE"\" -m32 -mno-sse -nostdlib -fno-reorder-functions -fno-strict-aliasing -fno-exceptions -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-zero-initialized-in-bss -fno-function-cse -fno-jump-tables --entry main -Wl,-N $BUILDID -fPIE -Wl,-Ttext -Wl,0 fat.c -o fatmini.o
objcopy -O binary fat.o fat.tmp
objcopy -O binary fatmini.o fatmini.tmp
sed -e '$s/\x00*$//' fat.tmp > fat
sed -e '$s/\x00*$//' fatmini.tmp > fatmini
rm fat*.o
date=`date -u +%Y-%m-%d`
zip -9 -r -q "../fat-$date.zip" fat fatmini
